import { Category, HeroBannerSlide, Product } from '../types';

export const HERO_SLIDES: HeroBannerSlide[] = [
  {
    id: 'h1',
    title: 'Big Billion\nSale is LIVE',
    subtitle: 'Electronics up to 70% off — Today only',
    cta: 'Shop Now',
    colors: ['#0A2E6E', '#1A5CB8'],
    iconName: 'flash',
    tag: '⚡  LIMITED TIME',
  },
  {
    id: 'h2',
    title: 'Fashion\nWeek 2026',
    subtitle: 'New arrivals from top brands',
    cta: 'Explore',
    colors: ['#4A148C', '#7B2FBE'],
    iconName: 'shirt',
    tag: '✨  NEW ARRIVALS',
  },
  {
    id: 'h3',
    title: 'Free Delivery\non All Orders',
    subtitle: 'No minimum order value required',
    cta: 'Start Shopping',
    colors: ['#BF360C', '#F47920'],
    iconName: 'cube',
    tag: '🚚  FREE DELIVERY',
  },
];

export const CATEGORIES: Category[] = [
  { id: 'electronics', name: 'Electronics',   icon: 'laptop-outline',          color: '#1A5CB8', bg: '#EEF4FF' },
  { id: 'fashion',     name: 'Fashion',        icon: 'shirt-outline',           color: '#7B2FBE', bg: '#F5EEFF' },
  { id: 'home',        name: 'Home',           icon: 'home-outline',            color: '#0E9F88', bg: '#E8FAF7' },
  { id: 'sports',      name: 'Sports',         icon: 'fitness-outline',         color: '#2E7D32', bg: '#EAF7EA' },
  { id: 'books',       name: 'Books',          icon: 'book-outline',            color: '#E65100', bg: '#FFF3E0' },
  { id: 'beauty',      name: 'Beauty',         icon: 'sparkles-outline',        color: '#C2185B', bg: '#FCE4EC' },
  { id: 'toys',        name: 'Toys',           icon: 'game-controller-outline', color: '#E53935', bg: '#FFEBEE' },
  { id: 'grocery',     name: 'Grocery',        icon: 'basket-outline',          color: '#F9A825', bg: '#FFFDE7' },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    title: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
    subtitle: 'Industry-leading noise cancellation, 30H battery',
    description:
      'Experience industry-leading noise cancellation with our most premium wireless headphones. Features Integrated Processor V1 for exceptional signal speed, 30-hour battery life, and crystal-clear call quality with Precise Voice Pickup Technology.',
    price: 24999,
    originalPrice: 34990,
    categoryId: 'electronics',
    rating: 4.8,
    reviewCount: 12847,
    stock: 45,
    badge: 'Best Seller',
    isFeatured: true,
    isDeal: true,
    tags: ['Wireless', 'Noise Cancelling', 'Bluetooth 5.2'],
  },
  {
    id: 'p2',
    title: 'Apple MacBook Air M3 Chip 15-inch Laptop',
    subtitle: 'Supercharged by Apple M3 chip',
    description:
      'MacBook Air with M3 chip delivers incredible performance with up to 18 hours of battery life. 15.3-inch Liquid Retina display with over a billion colours, 8GB RAM, 256GB SSD storage.',
    price: 114900,
    originalPrice: 134900,
    categoryId: 'electronics',
    rating: 4.9,
    reviewCount: 5231,
    stock: 12,
    badge: 'New',
    isFeatured: true,
    tags: ['Laptop', 'Apple', 'M3 Chip'],
  },
  {
    id: 'p3',
    title: 'Samsung Galaxy S24 Ultra 5G Smartphone',
    subtitle: '200MP Camera | Galaxy AI | S Pen',
    description:
      'The ultimate Galaxy AI experience. 200MP main camera captures every detail. Built-in S Pen for precision. Snapdragon 8 Gen 3 processor, 12GB RAM, 256GB storage.',
    price: 89999,
    originalPrice: 129999,
    categoryId: 'electronics',
    rating: 4.7,
    reviewCount: 8943,
    stock: 28,
    badge: 'Deal',
    isDeal: true,
    tags: ['Smartphone', 'Samsung', '5G'],
  },
  {
    id: 'p4',
    title: 'Logitech MX Master 3S Wireless Mouse',
    subtitle: 'For advanced creators, ultra-precise',
    description:
      'Ultra-fast MagSpeed electromagnetic scrolling. 8K DPI optical sensor tracks on any surface including glass. Whisper-quiet clicks. USB-C charging with 70-day battery life.',
    price: 7995,
    originalPrice: 9995,
    categoryId: 'electronics',
    rating: 4.6,
    reviewCount: 3421,
    stock: 60,
    badge: 'Best Seller',
    isFeatured: true,
    tags: ['Mouse', 'Wireless', 'MagSpeed'],
  },
  {
    id: 'p5',
    title: 'boAt Airdopes 141 True Wireless Earbuds',
    subtitle: '42H Playtime | ENx™ Noise Isolation',
    description:
      'True wireless earbuds with 42 hours total playtime. ENx™ noise isolation technology. BEAST™ Mode for ultra-low latency gaming. IPX4 water resistance.',
    price: 999,
    originalPrice: 2990,
    categoryId: 'electronics',
    rating: 4.2,
    reviewCount: 45621,
    stock: 200,
    badge: 'Deal',
    isDeal: true,
    tags: ['TWS', 'Earbuds', 'boAt'],
  },
  {
    id: 'p6',
    title: "Levi's Men's 511 Slim Fit Stretch Jeans",
    subtitle: 'Slim through seat and thigh, stretch denim',
    description:
      "Classic Levi's 511 slim fit jeans in stretch denim for a comfortable modern fit. Sits below waist, slim through seat and thigh, narrow leg opening.",
    price: 2299,
    originalPrice: 3999,
    categoryId: 'fashion',
    rating: 4.4,
    reviewCount: 18932,
    stock: 150,
    badge: 'Best Seller',
    isFeatured: true,
    tags: ["Men's", 'Jeans', "Levi's"],
  },
  {
    id: 'p7',
    title: 'Nike Air Max 270 Running Shoes',
    subtitle: "Nike's biggest heel Air unit yet",
    description:
      "Nike Air Max 270 features Nike's biggest heel Air unit for a supersoft ride. Engineered mesh upper provides lightweight breathability for all-day wear.",
    price: 8999,
    originalPrice: 12995,
    categoryId: 'fashion',
    rating: 4.5,
    reviewCount: 7823,
    stock: 35,
    badge: 'Deal',
    isDeal: true,
    tags: ['Nike', 'Running', 'Air Max'],
  },
  {
    id: 'p8',
    title: 'Philips HD9252/90 Air Fryer XXL Digital',
    subtitle: '6.2L | Rapid Air | 90% Less Fat',
    description:
      'Cook crispy food with up to 90% less fat using Rapid Air Technology. 6.2L capacity feeds a family of 4. Fat removal technology extracts and captures excess fat.',
    price: 9999,
    originalPrice: 18995,
    categoryId: 'home',
    rating: 4.6,
    reviewCount: 9234,
    stock: 40,
    badge: 'Deal',
    isDeal: true,
    isFeatured: true,
    tags: ['Air Fryer', 'Philips', 'Kitchen'],
  },
  {
    id: 'p9',
    title: 'Prestige PIC 16.0+ 2000W Induction Cooktop',
    subtitle: '8 preset menus | Auto shut-off | Child lock',
    description:
      'Powerful 2000W induction cooktop with 8 preset menus, feather touch control panel, auto shut-off, and child lock safety. Works with all induction-compatible cookware.',
    price: 2799,
    originalPrice: 4500,
    categoryId: 'home',
    rating: 4.3,
    reviewCount: 5421,
    stock: 80,
    tags: ['Cooktop', 'Prestige', 'Induction'],
  },
  {
    id: 'p10',
    title: 'Boldfit Gym Bag Sports Duffle Bag',
    subtitle: 'Water resistant | 40L | Separate shoe pocket',
    description:
      'Large 40L capacity gym bag with separate shoe compartment, water resistant polyester, and multiple storage pockets. Padded shoulder strap for comfort.',
    price: 799,
    originalPrice: 1999,
    categoryId: 'sports',
    rating: 4.1,
    reviewCount: 12430,
    stock: 120,
    badge: 'Best Seller',
    tags: ['Gym', 'Bag', 'Sports'],
  },
  {
    id: 'p11',
    title: 'Decathlon Corength Adjustable Dumbbell Set',
    subtitle: '2–24 kg | Replaces 6 pairs | Home gym',
    description:
      'Compact adjustable dumbbell system that replaces 6 pairs of dumbbells. Quick weight change from 2kg to 24kg. Ergonomic non-slip grip. Perfect for home workouts.',
    price: 15999,
    originalPrice: 22000,
    categoryId: 'sports',
    rating: 4.5,
    reviewCount: 2341,
    stock: 15,
    badge: 'New',
    isFeatured: true,
    tags: ['Dumbbells', 'Fitness', 'Decathlon'],
  },
  {
    id: 'p12',
    title: 'Atomic Habits by James Clear — Hardcover',
    subtitle: 'Build good habits & break bad ones',
    description:
      'Atomic Habits is a proven framework for getting 1% better every day. Over 15 million copies sold worldwide. James Clear distils the most fundamental information about habit formation.',
    price: 499,
    originalPrice: 799,
    categoryId: 'books',
    rating: 4.8,
    reviewCount: 34821,
    stock: 300,
    badge: 'Best Seller',
    isFeatured: true,
    tags: ['Self-help', 'Habits', 'Bestseller'],
  },
  {
    id: 'p13',
    title: 'Minimalist 10% Niacinamide Face Serum 30ml',
    subtitle: 'Pore reduction | Oil control | Fragrance-free',
    description:
      'High-strength 10% Niacinamide serum clinically proven to reduce enlarged pores, control oil, and improve uneven skin tone. Non-comedogenic, fragrance-free formula.',
    price: 399,
    originalPrice: 699,
    categoryId: 'beauty',
    rating: 4.4,
    reviewCount: 56890,
    stock: 500,
    badge: 'Best Seller',
    isFeatured: true,
    isDeal: true,
    tags: ['Serum', 'Skincare', 'Niacinamide'],
  },
  {
    id: 'p14',
    title: 'LEGO Classic Creative Bricks Box Set',
    subtitle: '900 pieces | Age 4+ | 33 build ideas',
    description:
      '900 piece LEGO classic brick box across 33 colours with 9 base plates. Includes building instructions for 33 inspiring models. Promotes creativity and STEM learning.',
    price: 2499,
    originalPrice: 3499,
    categoryId: 'toys',
    rating: 4.7,
    reviewCount: 4231,
    stock: 55,
    badge: 'New',
    tags: ['LEGO', 'Building', 'Creative'],
  },
  {
    id: 'p15',
    title: 'Organic India Raw Himalayan Honey 500g',
    subtitle: 'Unprocessed | 100% Natural | Antioxidant-rich',
    description:
      'Raw, unfiltered honey sourced from Himalayan farms. No added sugar, preservatives, or artificial flavors. Rich in natural antioxidants, enzymes, and minerals.',
    price: 349,
    originalPrice: 499,
    categoryId: 'grocery',
    rating: 4.5,
    reviewCount: 8923,
    stock: 200,
    tags: ['Honey', 'Organic', 'Natural'],
  },
  {
    id: 'p16',
    title: 'Samsung 55" 4K QLED Smart TV QN55Q80C',
    subtitle: 'Quantum Dot | HDR | Alexa Built-in',
    description:
      '55 inch QLED 4K Smart TV with Quantum Dot technology for a billion shades of brilliant colour. Neural Quantum Processor 4K, Quantum HDR, and Alexa built-in.',
    price: 54999,
    originalPrice: 89900,
    categoryId: 'electronics',
    rating: 4.6,
    reviewCount: 6721,
    stock: 8,
    badge: 'Deal',
    isDeal: true,
    isFeatured: true,
    tags: ['TV', 'Samsung', 'QLED'],
  },
  {
    id: 'p17',
    title: 'Noise ColorFit Pro 4 Smartwatch',
    subtitle: '1.78" AMOLED | GPS | Health Suite',
    description:
      'Advanced smartwatch with 1.78 inch AMOLED display, built-in GPS, heart rate monitor, SpO2 sensor, sleep tracking, and 7-day battery life.',
    price: 3499,
    originalPrice: 8999,
    categoryId: 'electronics',
    rating: 4.1,
    reviewCount: 23421,
    stock: 75,
    badge: 'Deal',
    isDeal: true,
    tags: ['Smartwatch', 'Noise', 'GPS'],
  },
  {
    id: 'p18',
    title: "H&M Women's Oversized Linen Blazer",
    subtitle: 'Relaxed fit | Summer 2026 collection',
    description:
      'Oversized blazer in quality linen fabric. Single button fastening, notch lapels, welt chest pocket, and welt side pockets. Perfect layering for any occasion.',
    price: 2799,
    originalPrice: 4999,
    categoryId: 'fashion',
    rating: 4.3,
    reviewCount: 3421,
    stock: 30,
    badge: 'New',
    isFeatured: true,
    tags: ["Women's", 'Blazer', 'H&M'],
  },
  {
    id: 'p19',
    title: 'Milton Thermosteel Insulated Water Bottle 1L',
    subtitle: '24H cold | 12H hot | Leak-proof',
    description:
      'Premium stainless steel insulated water bottle keeps beverages cold for 24 hours and hot for 12 hours. Leak-proof lid, BPA-free, food-grade stainless steel.',
    price: 599,
    originalPrice: 1299,
    categoryId: 'sports',
    rating: 4.4,
    reviewCount: 31920,
    stock: 180,
    badge: 'Best Seller',
    tags: ['Bottle', 'Milton', 'Insulated'],
  },
  {
    id: 'p20',
    title: 'WD 2TB My Passport Portable SSD USB-C',
    subtitle: '1050 MB/s | Hardware encryption | Compact',
    description:
      'Ultra-fast portable SSD with up to 1050MB/s read speeds. Password protection with hardware encryption. Shock resistant design. Compatible with PC, Mac, and USB-C devices.',
    price: 14999,
    originalPrice: 22990,
    categoryId: 'electronics',
    rating: 4.7,
    reviewCount: 4567,
    stock: 22,
    badge: 'Deal',
    isDeal: true,
    tags: ['SSD', 'Storage', 'USB-C'],
  },
];
